### ISSUE TITLE
Добавить больше возможностей работы с цветом 

### ISSUE THREAD

**Issue by devDebajo** [GyverLibs/GyverPortal#11]
Я может быть невнимательный, но пересмотрел все исходники и не нашел как из uint32_t цвета достать привычные RGB компоненты. И наоборот - перегнать RGB в uint32_t  - очень не хватает. Если оно где-то все же есть - ткните носом плиз

**Comment by GyverLibs** [comment]
Окей, добавлю

**Comment by devDebajo** [comment]
Благодарю

**Comment by GyverLibs** [comment]
заделал
