### ISSUE TITLE
OTA обновление?

### ISSUE THREAD

**Issue by sstopkin** [GyverLibs/GyverPortal#12]
Будет ли доступен компонент для OTA (over the air) обновления прошивки?

**Comment by sstopkin** [comment]
@GyverLibs Это, как минимум, file chooser, кнопка, логика под капотом (положить на флеш, заротировать значения из памяти, перезапустить).

**Comment by GyverLibs** [comment]
привет, а для esp32 как сделать?

**Comment by kbln** [comment]
я так понимаю, что и для 32 он есть https://github.com/espressif/arduino-esp32/tree/master/libraries/HTTPUpdateServer

**Comment by GyverLibs** [comment]
сервер далее сам разберётся, что делать с запросом /update ? И какие параметры там надо передать

**Comment by kbln** [comment]
да, он все сам делает!

![image](https://user-images.githubusercontent.com/8317386/164245216-98da058c-2909-4734-be4b-ee909b782582.png)
![image](https://user-images.githubusercontent.com/8317386/164245251-be797844-94a4-424e-bdda-10077f07c666.png)

**Comment by GyverLibs** [comment]
Аааа, прямо так! Окей. Планирую крупное обновление, тогда включу в релиз обязательно

**Comment by kbln** [comment]
Спасибо большое! Очень классная либа!

**Comment by GyverLibs** [comment]
Кстати
> httpUpdater.setup(&server); // перед server.begin()

server является публичным членом класса специально для расширенного использования библиотеки. Возможно не стоит жестко вшивать фичу в релиз, а просто написать об этом в доке)

**Comment by GyverLibs** [comment]
Если добавлять код в либу - работает, а если делать из скетча - нет?

**Comment by kbln** [comment]
ага, не компилилось извне

**Comment by kbln** [comment]
может задефайнить его? чтобы включали кому нужно

**Comment by GyverLibs** [comment]
Не компилилось - это какая ошибка

**Comment by kbln** [comment]
![image](https://user-images.githubusercontent.com/8317386/165331998-8afbfbc4-d0d3-4e6a-8567-956db4269c90.png)

**Comment by kbln** [comment]
ты прав, в таком виде прокатило:
```
httpUpdater.setup(&portal.server); 
```

ну и инициализация в начале
```
#include <ESP8266HTTPUpdateServer.h>
ESP8266HTTPUpdateServer httpUpdater; 
```
пожалуй, внутрь либы и правда можно не добавлять
спасибо, что помог разобраться!

**Comment by GyverLibs** [comment]
интегрирую в следующем обновлении
