### ISSUE TITLE
Обработка кликов по форме.

### ISSUE THREAD

**Issue by Juri4** [GyverLibs/GyverPortal#13]
Здравствуйте!
Пробую работу примера menuTabs.
Не могу найти причину странного отрабатывания логики.
при на жатии на кнопку  передается предыдущее значение.
при нажатии на туже кнопку  повторно,   передается правильное значение.
![image](https://user-images.githubusercontent.com/12124643/154198101-57161de6-a8e1-4c55-95fa-4abe89678e55.png)

https://user-images.githubusercontent.com/12124643/154198881-da7ea20a-73eb-4edd-a873-b74eda613011.mp4

**Comment by GyverLibs** [comment]
ESP32?

**Comment by Juri4** [comment]
Да она самая)

**Comment by GyverLibs** [comment]
Там большая проблема с есп32, не знаю получится ли сделать полную поддержку. 32 полностью ломает текущую логику библиотеки, то что работает на 8266 - не работает на 32

**Comment by Juri4** [comment]
Ок -понятно.

**Comment by GyverLibs** [comment]
Пофикшено в 2.0
