### ISSUE TITLE
Базовая авторизация

### ISSUE THREAD

**Issue by ZinovkinDmitry** [GyverLibs/GyverPortal#15]
Можно ли добавить возможность включения базовой авторизации? 
Как я понимаю, это по идее должно быть в методе showPage что то типа:
if(_is_enabled_auth)
   if (!server.authenticate(_www_username, _www_password)) 
	return server.requestAuthentication(DIGEST_AUTH, _www_realm, "Authentication Failed");

И вспомогательные методы: 
void setPassword(const char* www_password)
{
    _www_password = www_password;
}

void setUserName(const char* www_username)
{
    _www_username = www_username;
}

void onAuthMode()
{
   _is_enabled_auth = true;
}

void offAuthMode()
{
   _is_enabled_auth = false;
}

**Comment by GyverLibs** [comment]
Не сталкивался с таким, но изучу вопрос, фича полезная!

**Comment by GyverLibs** [comment]
интегрирую в следующем обновлении
