### ISSUE TITLE
Разбить на заголовочные файлы .h и .сpp

### ISSUE THREAD

**Issue by IlnurKashapov** [GyverLibs/GyverPortal#16]
При работе в Platformio при использовании библиотеки в отдельном файле (не main.cpp) проекта сталкиваешься с подобной ошибкой https://arduino.stackexchange.com/questions/71700/platformio-collect2-exe-error-ld-returned-1-exit-status

**Comment by GyverLibs** [comment]
Ну, что поделать)

**Comment by GyverLibs** [comment]
В следующем обновлении будет разбито на срр
