### ISSUE TITLE
обновление данных в поле ввода текста

### ISSUE THREAD

**Issue by Aleksey-748** [GyverLibs/GyverPortal#19]
Добрый день, подскажите как правильно обновлять данные в области add.TEXT("txt", "", valtext);, в общем задача следующая в данной области длинна строки не должна превышать 5 символов, по задумке если число символов в строке больше 5 то после обновления область add.TEXT("txt", "", valtext); в ней должно остаться только 5 символов, но как сделать обновление никак не разберусь. Заранее спасибо.

**Comment by GyverLibs** [comment]
Не отправлять больше 5 символов. Если отправляются неизвестные данные, то строку можно обрезать стандартными средствами
