### ISSUE TITLE
неявный лимит размерности графиков

### ISSUE THREAD

**Issue by Nordicx86** [GyverLibs/GyverPortal#20]
Необходимо или четко обозначить в документации Лимит числа точек в 256 единиц, или что на мой взгляд правильнее - показать формулу расчета максимального числа точек - вплоть до всей свободной памяти.

**Comment by GyverLibs** [comment]
Каких графиков?

**Comment by Nordicx86** [comment]
PLOT_STOCK - предел 255 точек
PLOT_STOCK_DARK - предел 255 точек

больше не компилируется:

C:\Users\nlr\Documents\Arduino\wifi_boiler\wifi_boiler.ino: In function 'void build()':
C:\Users\nlr\Documents\Arduino\wifi_boiler\wifi_boiler.ino:59:77: error: no matching function for call to 'Builder::PLOT_STOCK_DARK(const char [5], const char* [4], uint32_t [256], int16_t [4][256], int)'
   add.PLOT_STOCK_DARK<4, PLOT_SIZE>("TEMP", names, data.unix, data.vals, 100);

In file included from C:\Users\nlr\Documents\Arduino\wifi_boiler\wifi_boiler.ino:5:0:
C:\Users\nlr\Documents\Arduino\libraries\GyverPortal\src/GyverPortal.h:639:10: note: candidate: template<unsigned char ax, unsigned char am> void Builder::PLOT_STOCK_DARK(const char*, const char**, uint32_t*, int16_t (*)[am], int)
     void PLOT_STOCK_DARK(const char* id, const char** labels, uint32_t* times, int16_t vals[ax][am], int dec = 0) {

C:\Users\nlr\Documents\Arduino\libraries\GyverPortal\src/GyverPortal.h:639:10: note:   template argument deduction/substitution failed:
C:\Users\nlr\Documents\Arduino\wifi_boiler\wifi_boiler.ino:59:68: note:   cannot convert 'data.PlotData::vals' (type 'int16_t [4][256] {aka short int [4][256]}') to type 'int16_t (*)[0] {aka short int (*)[0]}'
   add.PLOT_STOCK_DARK<4, PLOT_SIZE>("TEMP", names, data.unix, data.vals, 100);

255 работает на ура., а вот 256 у же нет.

**Comment by Nordicx86** [comment]
```
#include <WiFi.h>
#include "time.h"

#include <GyverRelay.h>
#include <GyverPortal.h>
//#include <GyverNTC.h>
#include <C:\Users\nlr\Documents\Arduino\wifi_boiler\GyverNTC_w_ADC_LUT.h>


#define GMT_OFF 5       // часовой пояс, +3 для Москвы
#define LOG_PRD 16       // период обновления данных, секунд
#define PLOT_SIZE 256   // длина графика, точек

struct PlotData {
  int16_t   vals[4][PLOT_SIZE];
  uint32_t  unix[PLOT_SIZE];
};

PlotData data;  // храним всё в структуре для удобства

const char *names[] = {"Temp", "Target", "H_Up", "H_Down"};

int ThermistorPin, RelayPin, LEDPin;
double adcMax, Vs;
float Tc_g;

//Thermistor Parameters
double R1   = 100000.0; // voltage divider resistor value
double Beta = 3950.0;   // Beta value
double To   = 298.15;   // Temperature in Kelvin for 25 degree Celsius
double Ro   = 100000.0; // Resistance of Thermistor at 25 degree Celsius

GyverNTC    therm(35, Ro, Beta, 20, R1);
GyverRelay  regulator(REVERSE);
GyverPortal portal;

//Relay Parameters
int hysteresis = 5;
int setpoint = 40;
float k = 0.5;
bool ENA = 0;


//Portal ints
bool valSwitch = 0;
int valNum;
int valNum_hysteresis = hysteresis;
int valNum_setpoint = setpoint;
int valNum_LOG_Period = LOG_PRD;
float valNum_k = k;
int LOG_Period = LOG_PRD;


// билдер страницы
void build() {
  String s;
  BUILD_BEGIN(s);
  add.THEME(GP_DARK);
  add.PLOT_STOCK_DARK<4, PLOT_SIZE>("TEMP", names, data.unix, data.vals, 100);
  add.AREA_LOG(16);
  add.FORM_BEGIN("/update");
  add.NUMBER("hysteresis", "hysteresis", valNum_hysteresis);
  add.NUMBER("setpoint", "setpoint", valNum_setpoint);
  add.NUMBER("k", "k", valNum_k);  add.BREAK();
  add.SUBMIT("Submit POINTS");
  add.FORM_END();
  add.FORM_BEGIN("/graph_tune");
  add.NUMBER("LOG_Period", "LOG_Period", valNum_LOG_Period);
  add.SUBMIT("Submit GRAPH");
  add.FORM_END();
  BUILD_END();
}
```


вот кусок  кода....

**Comment by GyverLibs** [comment]
Естественно, там uint8_t тип данных. Могу сделать больше, это не проблема

**Comment by GyverLibs** [comment]
Можно скачать с Гита файлик gyverportal.h и заменить у себя в папке, релиз пока выпускать не буду

**Comment by Nordicx86** [comment]
да я собственно разобрался.... просто ни где не обозначено, что там это лимитировано - мне просто потребовалось 3к точек - вот и вылезло.
