### ISSUE TITLE
Обновление компонента по клику.

### ISSUE THREAD

**Issue by Aleksey-748** [GyverLibs/GyverPortal#21]
Добрый день возможноли обновление компонента по клику?

**Comment by GyverLibs** [comment]
Привет, какого например и в каком виде?

**Comment by Aleksey-748** [comment]
Есть слайдер, а сверху значение данного слайдера, при перемещении слайдера, это значение должно обновлятся. Или ввод в текстовое поле, после ввода текста данное поле должно стираться.

**Comment by GyverLibs** [comment]
Слайдер меняет значение переменной. Подключается обновление на лейбл и ему отправляется значение этой переменной

**Comment by Aleksey-748** [comment]
Но при этом запрос на обновление лейбла будет запрашиваться постоянно? Сейчас проект не под рукой, завтра покажу что я навыдумывал.

**Comment by Aleksey-748** [comment]
Понял, постоянное обнвление мне некатит, жалко конечно придется чтото думать как это обойти. Спасибо.
