### ISSUE TITLE
Включение LED

### ISSUE THREAD

**Issue by extinqued-resp** [GyverLibs/GyverPortal#25]
Привет, мне нужно при нажатии на switch включать/выключать led. Как это можно сделать?

**Comment by GyverLibs** [comment]
Привет, через update

**Comment by extinqued-resp** [comment]
этот метод же возвращает булев тип, если было обновление, а не сам обновляет

**Comment by GyverLibs** [comment]
Именно, но на это обновление нужно ответить, как в примере
