### ISSUE TITLE
Темы

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/GyverPortal#26]
Здравствуйте. Можно ли вместо стандартного файла themes.h из библиотеки подключить свой, если да то напишите как правильно это сделать (не переписывая библиотеку)...

**Comment by GyverLibs** [comment]
Привет, GP.THEME() принимает текст стилей из PROGMEM, поэтому создаёшь в таком же формате, кладёшь куда угодно, подключаешь в скетч и передаёшь переменную в GP.THEME()

**Comment by MalfurionST** [comment]
Ок спс
