### ISSUE TITLE
Новые стили

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/GyverPortal#28]
Здравствуйте, уже пару дней ковыряюсь в стилях CSS будут ли новые темы?
никак не могу осилить галочку и ползунок
если заинтересует могу скинуть стиль.
![Безымянный](https://user-images.githubusercontent.com/71415011/183297432-db4c6468-d5d4-4c0f-8658-6b9f25a3ebcb.png)

**Comment by GyverLibs** [comment]
Привет, от меня будет два стиля, остальное - на совести комьюнити) у меня в рабочей версии стили прилично переделаны, в том числе сделан полный редизайн слайдера. Такшта после свежего релиза жду стиль, выглядит приятно)

**Comment by GyverLibs** [comment]
![image](https://user-images.githubusercontent.com/84599917/183306084-a9d85ca4-3d02-49dc-a209-28e2612cbc1a.png)
