### ISSUE TITLE
Кастомна страница OTA Update

### ISSUE THREAD

**Issue by DenysChuhlib** [GyverLibs/GyverPortal#29]
Покопавшись в библиотеке ESP8266HTTPUpdateServer.h я придумал как можно сделать свою страницу:
```cpp
OTApage();
portal.enableOTA();
```
![image](https://user-images.githubusercontent.com/103110593/183480325-d7750060-570b-410e-8172-f58c397a86e2.png)

Правда отаётся только:
![image](https://user-images.githubusercontent.com/8317386/164245251-be797844-94a4-424e-bdda-10077f07c666.png)
но я не схотел всю (хоть она и небольшая) библиотеку ESP8266HTTPUpdateServer.h переписывать

Реализация:
```cpp
void OTApage() {
  OTApage(emptyString, emptyString);
}

void OTApage(const String& username, const String& password) {
//первый кусок ESP8266HTTPUpdateServer.h
  portal.server.on(PSTR("/ota_update"), HTTP_GET, [&]() {
    if (username != emptyString && password != emptyString && !portal.server.authenticate(username.c_str(), password.c_str()))
      return portal.server.requestAuthentication();

    // (тот самый portal.show())
    String s;
    _GP = &s;
    OTAbild();
    portal.server.send(200, F("text/html"), *_GP);
  });
}

void OTAbild() {
  GP_2.BUILD_BEGIN(PSTR("OTA update"));// BUILD_BEGIN с <title> в <head>
  GP.THEME(GP_DARK);
  GP.THEME(GP_2_DARK);

  GP.BLOCK_BEGIN();
  GP.TITLE(PSTR("OTA update"));
  GP.BLOCK_END();

  GP.BLOCK_BEGIN();
  GP.FORM_BEGIN("");
  
  GP.TITLE(PSTR("Firmware"));
  
  GP.BREAK();
  
  GP_2.UPLOAD_BUTTON(PSTR("firmware"), PSTR("Select file"), PSTR("Update Firmware"), "", PSTR(".bin,.bin.gz"));
  
  GP.FORM_END();

  GP.BREAK();
  GP.HR();

  GP.FORM_BEGIN("");
  
  GP.TITLE(PSTR("FileSystem"));

  GP.BREAK();
  
  GP_2.UPLOAD_BUTTON(PSTR("filesystem"), PSTR("Select file"), PSTR("Update FileSystem"), "", PSTR(".bin,.bin.gz"));
  
  GP.FORM_END();
  GP.BLOCK_END();

  BUILD_END();
}

void UPLOAD_BUTTON(const char* name, const char* value, const char* value_submit ,const char* label_id="" , const char* accept="") {
		*_GP += F("<div>");
		
		*_GP += F("<br>\n");
		
		*_GP += F("<label class=\"upload_button_label\" id=\"");
		*_GP += label_id;
		*_GP += F("\" for=\"");
		*_GP += name;
		*_GP += F("\">");
		*_GP += value;
		*_GP += F("</label>\n");
		
		*_GP += F("<input type=\"file\" class=\"upload_button_button\" name=\"");
		*_GP += name;
		*_GP += F("\" id=\"");
		*_GP += name;
		*_GP += F("\" accept=\"");
		*_GP += accept;
		*_GP += F("\" onclick=\"GP_click(this)\" onchange=\"this.parentElement.children[6].innerHTML = this.files[0].name\">\n");
		
		*_GP += F("<br>\n");
		*_GP += F("<br>\n");
		*_GP += F("<br>\n");
		
		*_GP += F("<label></label>");
		
		*_GP += F("</div>");
		
		*_GP += F("<br>");
		
		*_GP += F("<input type=\"submit\" formenctype=\"multipart/form-data\" value=\"");
		*_GP += value_submit;
		*_GP += F("\">\n");
	}

const char GP_2_DARK[] PROGMEM =
"<style type=\"text/css\">\n"
".upload_button_label {font-size:28px;padding: 14px 12px;background-color:#1300e3;border:none;border-radius:8px;color:white;cursor:pointer;}\n"
".upload_button_button {width: 0.1px; height: 0.1px; opacity: 0; overflow: hidden; position: absolute; z-index: -1;}\n"
"</style>\n";
```
Стиль конешто так себе, но я не заморачивался:)

**Comment by GyverLibs** [comment]
может поковыряю, но вроде не сильно важная фича) в следующем обновлении появится нативный механизм загрузки и скачивания файлов

**Comment by GyverLibs** [comment]
Так стоять, а почему ты из `PSTR()` прибавляешь напрямую к строке??
> However use of these pointers, without correct 32bit alignment you will cause a segmentation fault and the ESP8266 will crash. You must read from the flash 32 bit aligned.

https://arduino-esp8266.readthedocs.io/en/latest/PROGMEM.html

**Comment by DenysChuhlib** [comment]
Потому что F() он как String а PSTR() как const char*. А что не так?

**Comment by GyverLibs** [comment]
Я выше скинул доку и цитату из неё. `const char*` не означает, что можно читать значение напрямую. Либо копировать в буфер RAM, либо через `FPSTR()`, иначе может вылететь ексепшен и будет перезагрузка

**Comment by DenysChuhlib** [comment]
Ах да можно просто const PROGMEM char* = "hello" и он будет как обычный const char*

**Comment by DenysChuhlib** [comment]
Ну у меня работало и я не обращал внимания)

**Comment by DenysChuhlib** [comment]
А как будет правельно?

**Comment by DenysChuhlib** [comment]
Я так понял, от так надо?
*_GP += FPSTR(label_id);

**Comment by GyverLibs** [comment]
Да, можно так

**Comment by GyverLibs** [comment]
Но если передать обычную строку и сделать её fpstr - скорее всего всё сломается опять же

**Comment by DenysChuhlib** [comment]
Нужно проверить

**Comment by GyverLibs** [comment]
а на что триггерится библиотека ESP8266HTTPUpdateServer? В каком месте она перехватывает файл и делает OTA? На название формы, часть запроса, или где

**Comment by DenysChuhlib** [comment]
В ESP8266HTTPUpdateServer-impl.h через server.on ставиться на HTTP_POST две функции. 1 вызываеться при отправке формы, 2 вызываеться когда загружаеться файл

**Comment by DenysChuhlib** [comment]
Я сделал под новою версию)
Инициализация:
```cpp
portal.attachUploadManual(upload); //setup()

void upload(HTTPUpload& upl, GyverPortal& portal) {// любо где в скэтче
  OTAupload(upl, portal);
}

if (portal.request(F("/ota_update"))) OTAbild(); // в конструктор страницы
```
И добавить (можно файлом .ino)
```cpp

String OTAupdaterError;
bool OTAend;

void OTAupload(HTTPUpload& upload, GyverPortal& portal) {
  if (OTAend) return;

  if (!(upload.name == "OTAfileSystem" || upload.name == "OTAfirmware")) return;

  if (!(upload.filename.endsWith(F(".bin")) || upload.filename.endsWith(F(".bin.gz")))) {
    OTAupdaterError = F("type file .bin or .bin.gz");
    OTAend = true;
    return;
  }

  if (upload.status == UPLOAD_FILE_START) {
    OTAupdaterError.clear();

    if (upload.name == "OTAfileSystem") {
      size_t fsSize = ((size_t) &_FS_end - (size_t) &_FS_start);
      close_all_fs();
      if (!Update.begin(fsSize, U_FS)) { //start with max available size
        StreamString str;
        Update.printError(str);
        OTAupdaterError = str.c_str();
        OTAend = true;
      }
    } else if (upload.name == "OTAfirmware") {
      uint32_t maxSketchSpace = (ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000;
      if (!Update.begin(maxSketchSpace, U_FLASH)) { //start with max available size
        StreamString str;
        Update.printError(str);
        OTAupdaterError = str.c_str();
        OTAend = true;
        return;
      }
    } else return;
    WiFiUDP::stopAll();
  } else if (upload.status == UPLOAD_FILE_WRITE && !OTAupdaterError.length()) {
    if (Update.write(upload.buf, upload.currentSize) != upload.currentSize) {
      StreamString str;
      Update.printError(str);
      OTAupdaterError = str.c_str();
      OTAend = true;
    }
  } else if (upload.status == UPLOAD_FILE_END && !OTAupdaterError.length()) {
    if (!Update.end(true)) { //true to set the size to the current progress
      StreamString str;
      Update.printError(str);
      OTAupdaterError = str.c_str();
    }
    OTAend = true;
  } else if (upload.status == UPLOAD_FILE_ABORTED) Update.end();
}

void OTAbild() {
  GP.BUILD_BEGIN(400);
  GP.THEME(GP_DARK);

  GP.BLOCK_BEGIN();
  GP.TITLE(F("OTA update"));
  GP.BLOCK_END();

  GP.BLOCK_BEGIN();
  if (!OTAend) {

    GP.TITLE(F("Firmware"));

    GP.BREAK();

    GP.LABEL(F("Update Firmware")); GP.FILE_UPLOAD(F("OTAfirmware"));// F(".bin,.bin.gz"));

    GP.BREAK();
    GP.HR();

    GP.TITLE(F("FileSystem"));

    GP.BREAK();

    GP.LABEL(F("Update FileSystem")); GP.FILE_UPLOAD(F("OTAfileSystem"));  //F(".bin,.bin.gz"));


  } else if (OTAupdaterError.length()) {
    GP.TITLE(String(F("Update error: ")) + OTAupdaterError);
    GP.BUTTON_LINK(F("/ota_update"), F("Refresh"));
  } else {
    GP.TITLE(F("Update Success!"));
    GP.TITLE(F("Rebooting..."));
    GP.BUTTON_LINK(F("/ota_update"), F("Refresh"));
  }

  GP.BLOCK_END();

  BUILD_END();

  if (OTAend && !OTAupdaterError.length() && !Update.hasError()) {
    portal.server.client().stop();
    delay(100);
    ESP.restart();
  } else if (OTAend && OTAupdaterError.length()) {
    OTAend = false;
    OTAupdaterError.clear();
  }
}
```

**Comment by DenysChuhlib** [comment]
Я думаю вы придумаете как это интегрировать)

**Comment by DenysChuhlib** [comment]
Это полностю без библы ESP8266HTTPUpdateServer.h, на esp32 не могу проверить но написано, там так само)

**Comment by GyverLibs** [comment]
Но зачем

**Comment by DenysChuhlib** [comment]
Я хотел сделать что бы оно было в стиле GyverPortal и у меня получилось, теперь можно оключить обновление прошивки и обновлять файлову систему, либо на оборот. Фактически полный доступ фантазии.
Можете просто как пример впихнуть, может кого-то заинтересует)

**Comment by DenysChuhlib** [comment]
От если что пример (снова) а так можно закрывать данное issue)
[customOTAupdate.zip](https://github.com/GyverLibs/GyverPortal/files/9434993/customOTAupdate.zip)

**Comment by Serega88kos** [comment]
тоже собирался копать эту страницу, не хватает кнопки вернуться в начало, было бы удобнее)

**Comment by Serega88kos** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/Update/examples/HTTPS_OTA_Update/HTTPS_OTA_Update.ino
сертификат может еще добавить для портала?

**Comment by DenysChuhlib** [comment]
> тоже собирался копать эту страницу, не хватает кнопки вернуться в начало, было бы удобнее)

Так добавь)

**Comment by GyverLibs** [comment]
> customOTAupdate.zip

не смогу добавить в релиз, слишком много конфликтов и отличий между 8266 и 32. Пока оставлю как есть

**Comment by DenysChuhlib** [comment]
Я зделал отдельным .h файлом, после проверки на esp32 скину)

**Comment by GyverLibs** [comment]
Короче, придумал ох.енно простой и надёжный трюк, как пружина от дивана. Делаем кастом форму-кнопку аплоада, в action передаем тот же урл, который указан в библиотеке httpupdate, и названия формы как в библиотеке, firmware и filesystem. В итоге библиотека httpupdate просто перехватит загрузку и обновит прошивку, без костылей, смс и регистрации

**Comment by GyverLibs** [comment]
И всё)

```cpp
    void FILE_UPLOAD_RAW(const String& name, const String& text = "", const String& accept = "", const String& options = "", const String& action = "/GP_upload") {
        String s;
        s.reserve(250);
        s += F("<form action='");
        s += action;
        s += F("' method='POST' enctype='multipart/form-data' id='");
        s += name;
        s += F("_form' style='display:flex;justify-content:center;'>\n"
        "<div id='ubtn' onclick='saveFile(\"");
        s += name;
        s += F("_inp\")'>");
        s += text;
        s += F("</div>\n"
        "<div id='ubtnclr'><input ");
        s += options;
        s += F("name='");
        s += name;
        if (accept.length()) {
            s += F("' accept='");
            s += accept;
        }
        s += F("' id='");
        s += name;
        s += F("_inp' type='file' onchange='GP_subm(\"");
        s += name;
        s += F("_form\")'/></div>\n"
        "</form>\n");
        SEND(s);
    }
    
    void FILE_UPLOAD(const String& name, const String& text = "", const String& accept = "") {
        FILE_UPLOAD_RAW(name, "📄 " + text, accept, F("multiple "));
    }
    
    void FOLDER_UPLOAD(const String& name, const String& text = "") {
        FILE_UPLOAD_RAW(name, "📁 " + text, "", F("multiple webkitdirectory allowdirs "));
    }
	
	void OTA_FIRMWARE(const String& text = "") {
        FILE_UPLOAD_RAW(F("firmware"), "🧱 " + text, F(".bin,.bin.gz"), "", F("/ota_update"));
    }
	
	void OTA_FILESYSTEM(const String& text = "") {
        FILE_UPLOAD_RAW(F("filesystem"), "💽 " + text, F(".bin,.bin.gz"), "", F("/ota_update"));
    }
```

**Comment by DenysChuhlib** [comment]
А я уже утилиту сделал для GyverPortal. Вышло лутше чем стандартные библы двох esp. Плюс можно выполнить какие-то действия перед перезагрузкой.

**Comment by DenysChuhlib** [comment]
Решение простое и FILE_UPLOAD_RAW это хорошо, но я легких путей не ищу. Темболее уже сделано просто нужно проверить.

**Comment by DenysChuhlib** [comment]
А и главное можно задать имя скетча, а то постоянно загружал не тот и нужно было с ноутом стоять час и ждать когда оно выгрузится(

**Comment by DenysChuhlib** [comment]
Ось я проверил полностью filesystem and firmware на esp8266. 32 будет через пару дней, можете вы проверить, компиляция успешна но работает ли оно.
Эту утилиту можно встроить в GyverPortal а можно сделать отдельно.
[CustomOTA.zip](https://github.com/GyverLibs/GyverPortal/files/9590645/CustomOTA.zip)

Инициализация
```cpp
#define GP_NO_OTA 1
#include <GyverPortal.h>
#include <CustomOTA.h>
GyverPortal portal;
```

setup();
```cpp
OTAUpdate.begin(&portal);
portal.start();
```

**Comment by GyverLibs** [comment]
Я понимаю что ты лёгких путей не ищешь, но весь код который ты раньше предлагал - ломает библиотеку, и добавить его в исходном виде я в принципе не мог. Посмотрим

**Comment by DenysChuhlib** [comment]
> весь код который ты раньше предлагал

Потому что там были ошибки и ещё на 32 очень много библиотек упрощено и проблема было в F()
на 8266 не работает F() + F() но работает F() + String() а на 32 только String() + String() и всё

**Comment by DenysChuhlib** [comment]
А 1 ошибка с F() даёт штук 10 ошибок в консоль, хз почему

**Comment by DenysChuhlib** [comment]
Надо было сразу утилитой делать)

**Comment by DenysChuhlib** [comment]
Да и если бы была эта затея безсмысленой я бы и не брался, а так мне оно помогает от неуважности загрузить не той бинарник как миниму)

**Comment by GyverLibs** [comment]
Читай уроки по String. Нельзя складывать F + F или F + char. Первым слагаемым должен быть String, осталные уже любого другого типа

**Comment by DenysChuhlib** [comment]
я уже это понял

**Comment by DenysChuhlib** [comment]
но на 32 F + String некак нельзя

**Comment by DenysChuhlib** [comment]
Учусь на своих ошибках.

**Comment by DenysChuhlib** [comment]
Я тут решил в бинарник заглянуть 8266 и поискал текст что в F и он только в одном экземпляре если они полностью идентичны

**Comment by DenysChuhlib** [comment]
Я проверил и доделал обновление fs а то на esp32 в HTTPWebUpdate для того чтобы обновить файловую систему нужно чтобы был запущен SPIFFS если выгружен SPIFFS, а с LittleFS вопще некак было. А теперь моя универсальная библа-утилита сама проверяет и запускает по необходимости.

Полностью проверена на esp8266 и esp32

Я придумал уже как ее встроить в GyverPortal:

1. Разместить подключение файлов таким образом:
```cpp
#include "builder.h"
String* _gp_uri;
Builder add;    // legacy
Builder GP;
#include "themes.h"
#include "objects.h"
#include "buildMacro.h"
#include "legacy.h"
#include "log.h"
#include "CustomOTA.h"
#include "portal.h"
```
2. Потом в класcе GyverPortal
```cpp
 #ifndef GP_NO_OTA
CustomOTAUpdate OTAUpdate;
#endif

void enableOTA(const String& login, const String& pass) {
        #ifndef GP_NO_OTA
        OTAUpdate.begin(&server, login, pass);
        #endif
    }

void enableOTA() {
       enableOTA("","");
    }
```

И всё, можно теперь через portal.OTAUpdate настраивать если нужно.

>PS: CustomOTA сам подтянет нужные библиотеки

[CustomOTA.zip](https://github.com/GyverLibs/GyverPortal/files/9641892/CustomOTA.zip)

**Comment by GyverLibs** [comment]
Но зачем, если хорошо работает мой вариант с кнопками, которые перенаправляют на встроенную библу?

**Comment by DenysChuhlib** [comment]
1 на esp32 стандартная либа не может загрузить бинарник с littlefs
2 поудобнее будет

**Comment by DenysChuhlib** [comment]
> 1 на esp32 стандартная либа не может загрузить бинарник с littlefs 
Может только если загружен SPIFFS, потому что библиотека проверят размер именно SPIFFS.

**Comment by GyverLibs** [comment]
То есть если подключить библу httpupdate и littlefs в одном скетче - не скомпилит?

**Comment by DenysChuhlib** [comment]
Скомпилит просто будет некак обновить файлы через бинарник

**Comment by GyverLibs** [comment]
Но почему?

**Comment by DenysChuhlib** [comment]
У меня в файле одновременно поключены SPIFFS и LittleFS.

**Comment by DenysChuhlib** [comment]
Потому что если прошит SPIFFS то LittleFS.totalBytes() выдаст 0 и наоборот

**Comment by DenysChuhlib** [comment]
А в стандартной библе только SPIFFS проверят размер

**Comment by GyverLibs** [comment]
Ой порнуха. То есть использование стандартной ota диктует юзера файловую систему, которой он должен пользоваться в скетче?

**Comment by DenysChuhlib** [comment]
Да только SPIFFS и обезательно с вызваным begin()

**Comment by DenysChuhlib** [comment]
У меня можно даже без begin

**Comment by DenysChuhlib** [comment]
Всё таки не зря затеял

**Comment by DenysChuhlib** [comment]
Но эта проблема только на esp32

**Comment by DenysChuhlib** [comment]
Вопщем с стандартной на esp32 httpwebupdate можно загрузить скетч и обновить SPIFFS без LittleFS.

**Comment by GyverLibs** [comment]
Так, ну выглядит вроде уже легально, отличная работа! Как будет на руках 32, протестирую

**Comment by GyverLibs** [comment]
чутка поправил, проверил на 8266 - работает

**Comment by DenysChuhlib** [comment]
Хорошо

**Comment by DenysChuhlib** [comment]
> чутка поправил

Что именно?

**Comment by DenysChuhlib** [comment]
Ага вижу, ок
