### ISSUE TITLE
Буфер uri

### ISSUE THREAD

**Issue by DenysChuhlib** [GyverLibs/GyverPortal#32]
Добавте возможность изменять буфер uri который нужен для идентификации страницы и форм, для тех случаев когда название формы или страницы большое:
```cpp
GyverPortal(uint8_t buf_n = 15) {
    _uri.reserve(buf_n);
}
```
Спасибо за внимание

**Comment by GyverLibs** [comment]
Uri хранится в String, это не имеет смысла)
