### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by DenysChuhlib** [GyverLibs/GyverPortal#37]
У меня есть предложение убрать в portal.h start(); 
```cpp
if (_uri.startsWith(F("/favicon.ico"))) {       // иконка
                server.send(200, "text/plane");             // игнорируем
                return;
            }
```
Так как можно чтобы овтозагрузчик или свой загрузчик попытался его скачать
И таким образом можно будет свою иконку сайту ставить 😁

**Comment by GyverLibs** [comment]
Для этого юзер будет обязан закинуть файл в спиффс и подключить даунлоадер. Это в 90% случаях не нужно

**Comment by DenysChuhlib** [comment]
Если его не будет автозагрузчик просто отравит пустоту

**Comment by DenysChuhlib** [comment]
а если выключена загрузка та пусть срабатывает как и было

**Comment by DenysChuhlib** [comment]
Я придумал, переместите это 

 ```c++
 if (_uri.startsWith(F("/favicon.ico"))) {       // иконка
                 server.send(200, "text/plane");             // игнорируем
                 return;
             }
 ```
после загрузчика и всё

**Comment by DenysChuhlib** [comment]
Если GP_NO_DOWNLOAD то просто будет работать как и было

**Comment by GyverLibs** [comment]
я сделал так
```cpp
  #ifndef GP_USE_FAVICON
  } else if (_uri.startsWith(F("/favicon.ico"))) {    // иконка
      server.send(200, "text/plane");
      return;
  #endif
```
