### ISSUE TITLE
Работа portal.log.println при нескольких открытых окнах

### ISSUE THREAD

**Issue by BearScience** [GyverLibs/GyverPortal#39]
**Приветствую!**

Не знаю, баг ли это, или же просто особенность работы. Опишу ситуацию как я сделал:
 ```
GP.TEXT("txt", "text");      GP.BREAK();
 GP.AREA_LOG(30);
 
 if (portal.click("txt")) {
      val = portal.getString("txt");
      Serial.print("Text: ");
      Serial.println(val);
    }
  portal.log.println(val);
```
Соответственно, если я ввожу в текстовое поле что то - оно тут же появляется в AREA LOG.

Это работает в браузере на ПК, это работает в браузере в телефоне, но не работает если страница открыта одновременно в телефоне и браузере.
Если она открыта одновременно и там и там - то в AREA LOG данные отображается только в браузере ПК.
Это не критично, но я подумал вдруг это баг, и решил сообщить. 
Если это нормальная работа, и так задумано - то можно удалить данный пост.
Благодарю

**Comment by GyverLibs** [comment]
Привет, да, это нормально. Браузер запрашивает данные по таймеру, есп отправляет всё что накопилось в буфере на текущий момент. Соответственно один браузер получает все свежие данные, а второй - уже пустыня либо данные будут разделяться если отправляются на протяжении периода обновления. Допишу об этом в документации
