### ISSUE TITLE
Проверка обривания upload

### ISSUE THREAD

**Issue by DenysChuhlib** [GyverLibs/GyverPortal#41]
Уже сразу есть решение. Просто добавить параметр uploadAborted() и при обрывании запускать action и проверять его. Это как с начало и концом выгрузки.

>Просто если бы у меня не показывался размер я бы и не заметил что оборвался.

**Comment by GyverLibs** [comment]
Подключить функцию на аборт?

**Comment by DenysChuhlib** [comment]
Да

**Comment by DenysChuhlib** [comment]
bool uploadAborted() возращает в action() 1 если оборвалось

**Comment by GyverLibs** [comment]
Это "не подключить функцию на аборт". Я сделал как с beforeRestart

**Comment by DenysChuhlib** [comment]
Ну ладно.

**Comment by DenysChuhlib** [comment]
можите на гит добавить?

**Comment by GyverLibs** [comment]
запушил

**Comment by DenysChuhlib** [comment]
Я не про CostomOTA а про аплоад файлов в GyverPoartal

**Comment by DenysChuhlib** [comment]
Отмените commit

**Comment by DenysChuhlib** [comment]
> аплоад файлов в GyverPoartal

В portal.h

**Comment by GyverLibs** [comment]
> Отмените commit

зачем, пусть будет для отладки

**Comment by GyverLibs** [comment]
А чем поможет знание того что файл абортнулся?

**Comment by DenysChuhlib** [comment]
Удалить неполноценный файл

**Comment by GyverLibs** [comment]
возможно. Тогда уж и качать надо в .bak файл, а потом в случае успеха заменять если есть

**Comment by DenysChuhlib** [comment]
просто fs.remove(); в рядке 151 portal.h и всё

**Comment by DenysChuhlib** [comment]
> просто fs.remove(upload.filename); в рядке 151 portal.h и всё

А лутше action вызывать я сам себе допишу действия

**Comment by DenysChuhlib** [comment]
> > Отмените commit
> 
> зачем, пусть будет для отладки

Оно и так на страницу выводит сообщение про abort

**Comment by GyverLibs** [comment]
> Оно и так на страницу выводит сообщение про abort

ломать не строить, вдруг пригодится

**Comment by GyverLibs** [comment]
> просто fs.remove(upload.filename); в рядке 151 portal.h и всё

то есть если я закидываю файл который уже есть с целью перезаписать, и если он недокачается библиотека его просто удалит?)

**Comment by DenysChuhlib** [comment]
ну да

**Comment by DenysChuhlib** [comment]
> просто fs.remove(upload.filename); в рядке 151 portal.h и всё

точнее fs.remove('/' + upl.filename);

**Comment by GyverLibs** [comment]
ну не

**Comment by DenysChuhlib** [comment]
что?

**Comment by DenysChuhlib** [comment]
А кому нужно будет удалять, как я

**Comment by GyverLibs** [comment]
по хорошему нужно качать во временный файл, но это нужно на усмотрение юзера делать

**Comment by DenysChuhlib** [comment]
И так згодиться

**Comment by GyverLibs** [comment]
запушил

**Comment by DenysChuhlib** [comment]
Спасибо
