### ISSUE TITLE
VSCode + Platformio

### ISSUE THREAD

**Issue by olegvresh** [GyverLibs/GyverPortal#42]
Привет .
на VS Code + Platformio и возникла такая проблема:
При компиляции линковщик ругается на multiple definition методов библиотеки.
на каждй метод выдает такое :

./../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp12e\src\schedule\schedule.cpp.o: in function `_Z10encodeDate6GPdate':

schedule.cpp:(.text._Z10encodeDate6GPdate+0x30): multiple definition of `_Z10encodeDate6GPdate'; .pio\build\esp12e\src\main.cpp.o:main.cpp:(.text._Z10encodeDate6GPdate+0x30): first defined here

../../../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe

``` cpp
// file name :   main.cpp
#include <Arduino.h>
#include <GyverPortal.h>
#include <someCode.h>

void setup() 
{
  // put your setup code here, to run once:
}

void loop() 
{
  // put your main code here, to run repeatedly:
}
```

``` cpp
 /*file name:   someCode.h  в этом файле подключаем GyverPortal что бы объявить переменные с типами данных GPdate GPtime из библиотеки  */

#pragma once
#include <Arduino.h>
#include <GyverPortal.h>

class MyObj
{
public:
    GPdate startDate; //дата начала работы автомата
    GPtime startTime; //время начала работы автомата
    GPdate endDate;   //дата завершения работы автомата
    GPtime endTime;   //время завершения работы автомата
    void someMethod();
private:
};
```
``` cpp
// file name:   someCode.cpp
#include <Arduino.h>
#include <someCode.h>
void MyObj ::someMethod()
{
    //some code
}
```
Если в файле main.cpp закоментить подключение (#include "someCode.h") все собирается.
или же отключаю Gyver Portal и все объявления с ним связанные и тоже все работает
Пока писал, проверил с Gyver NTC та же история... multiple definition ...
**Короче**,  невозможно подключить библиотеку к двум и более файлам проекта. Ровно как и подключить заголовочный файл к которому уже подключена библиотека. 
Склонен считать,  причиной этому является то, что много реализации написано в заголовочных файлах. Если я парвильно понимаю, то в файлах.h ее вообще не должно быть. Только объявления. Проверил эту свою теорию на других библиотеках(TimeLib, ESP32Time), где в .h файлах нет логики. Там все работает, и инклудить их можно хоть в каждом файле проекта.

**Comment by GyverLibs** [comment]
Возможно стоит настроить компилятор. Реализация, внесённая в класс, часто встречается в библиотеках, в этом нет должно быть проблемы. Проблема будет если реализация вынесена из класса в .h файле, или если это просто голые функции (вообще без класса) в h файле. Я платформио не пользуюсь, больше ничего подсказать не могу.

P.S. а какая версия библиотеки? Релизная, или из репозитория (бета v3)? В 3 версии всё разбито на файлы более правильно

**Comment by GyverLibs** [comment]
на версии 3 компилится?

**Comment by GyverLibs** [comment]
кажется понял в чём дело, в следующем обновлении будет исправлено

**Comment by olegvresh** [comment]
Может расскажешь? ;)
Дико не хочется писать веб морду своими руками :)

**Comment by GyverLibs** [comment]
В GyverNTC нет причин для такого поведения. А здесь в главном хэдере были объявлены переменные, их надо вынести в .cpp
[GyverPortal.zip](https://github.com/GyverLibs/GyverPortal/files/9727808/GyverPortal.zip)

**Comment by olegvresh** [comment]
Вроде даже заработало. Спасибо за отзывчивость!

**Comment by GyverLibs** [comment]
В GyverNTC наверное другая проблема - при попытке создать объект GyverNTC внутри класса с вызовом конструктора, то есть
```cpp
class MyClass {
  GyverNTC therm(0, 10000, 3435);
}
```
Приведёт к ошибке. А пустой конструктор в библиотеке не предусмотрен.. видимо надо добавить setPin и прочее..

**Comment by olegvresh** [comment]
> В GyverNTC наверное другая проблема - при попытке создать объект GyverNTC внутри класса с вызовом конструктора, то есть
> 
> ```c++
> class MyClass {
>   GyverNTC therm(0, 10000, 3435);
> }
> ```
> 
> Приведёт к ошибке. А пустой конструктор в библиотеке не предусмотрен.. видимо надо добавить setPin и прочее..

Спасибо. Доберусь проверю.
