### ISSUE TITLE
Сохранение данных

### ISSUE THREAD

**Issue by sae74** [GyverLibs/GyverPortal#43]
Вопрос такой:
Как сохранять введенные значения через WEB морду?
Они автоматически сохраняются в памяти и восстанавливаются после перезагрузки или самому нужно это реализовывать?

**Comment by GyverLibs** [comment]
Посмотреть хотя бы один пример и всё станет понятно)

Также есть документация
https://github.com/GyverLibs/GyverPortal/wiki/%D0%A5%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B9

**Comment by sae74** [comment]
Спасибо.
Я еще не изучал, только "наткнулся" на проект)

**Comment by GyverLibs** [comment]
Аа)
