### ISSUE TITLE
Скрипты графиков.

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/GyverPortal#45]
Здравствуйте. Насколько я понимаю скрипты графиков пока ещё скачиваются из интернета?

**Comment by GyverLibs** [comment]
Привет, у графиков есть оффлайн режим с загрузкой скриптов из памяти

**Comment by MalfurionST** [comment]
void PLOT_STOCK(const String& id, const char** labels, uint32_t* times, int16_t vals[ax][am], int dec = 0, int height = 400, bool local = 0) {
        *_gp_page += F("<script src='");
        
        if (local) *_gp_page += F("/gp_data/PLOT_STOCK.js");

Разве **bool local = 0** не значит что это условие всегда будет ложным?

**Comment by GyverLibs** [comment]
Нет, не означает. Это значение параметра по умолчанию, C++
