### ISSUE TITLE
ESP32 platform.io

### ISSUE THREAD

**Issue by Juri4** [GyverLibs/GyverPortal#5]
Буду премного благодарен, если выложите, рабочую версию примера wifiLogin для ESP32 и platform.io

Перенес void loginPortal() выше  void setup()
сменил пин кнопки.
Стало компилироваться и прошиваться.
AP  запускается подключается, в терминале Portal start
но зайти на 192.168.4.1 не получается
Заранее благодарю

**Comment by AlexGyver** [comment]
у меня нет есп32 для тестов. У есп32 айпишник AP по умолчанию точно 192.168.4.1? Можно его поменять в
```cpp
WiFi.softAPConfig(IPAddress(192.168.4.1), IPAddress(255.255.255.0), IPAddress(255.255.255.0));
```

**Comment by bad040** [comment]
Отличная библиотека. Работает на 8266 но на esp32 не отображает страницы. Пробовал как на ESP32devkit1 так и на ESP32S2. Проблема как с платформио так и с ардуино IDE

**Comment by GyverLibs** [comment]
Видимо еспшки не очень совместимы между собой. Ждём когда кто нибудь починит, у меня нет есп32

**Comment by GyverLibs** [comment]
усё, сделал, работает на esp32

**Comment by bad040** [comment]
Огромное спасибо!!! Буду проверять

**Comment by Juri4** [comment]
Класс заработало!!!

**Comment by bad040** [comment]
Еще раз огромное спасибо, работает

**Comment by GyverLibs** [comment]
Сегда пожалуйста)
