### ISSUE TITLE
getInt() возвращает всегда 0 (ESP32)

### ISSUE THREAD

**Issue by AtariVC** [GyverLibs/GyverPortal#51]
Не могу понять в чем проблема, пытаюсь получить значение с нумбера, но в переменную всегда 0 записывается.
Конфиг:

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = gyverlibs/GyverPortal@^3.2

Код:

int freqa = 500;
void build(){
  GP.BUILD_BEGIN(600);
  GP.THEME(GP_DARK);
  GP.NUMBER("freqa", "", freqa);
  GP.BUTTON("run_st_btn", "RUN");
  GP.BUILD_END();
}
void action(){
  if(portal.click("run_st_btn")){
    freqa = portal.getInt("freqa");
    Serial.println(freqa);
  }
}

**Comment by GyverLibs** [comment]
Работает в точности как запрограммировано ;) получение инта делается внутри проверки на клик другого компонента
