### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by osintaras** [GyverLibs/GyverPortal#53]
Все платы, библиотеки, ide обновлены. Но все равно выдает ошибку при компиляции примера из библиотеки
https://disk.yandex.ru/i/mwQuHMwC4nYKeA

In file included from c:\sketches\libraries\GyverPortal\src/CustomOTA.h:4:0,
                 from c:\sketches\libraries\GyverPortal\src/portal.h:16,
                 from c:\sketches\libraries\GyverPortal\src/GyverPortal.h:65,
                 from C:\Users\Taras\AppData\Local\Temp\.arduinoIDE-unsaved20221015-17264-3ndpck.n9yqh\actionUpdate\actionUpdate.ino:6:
c:\sketches\libraries\GyverPortal\src/builder.h: In member function 'void Builder::_showFiles(fs::FS*, const String&, uint8_t)':
c:\sketches\libraries\GyverPortal\src/builder.h:922:49: error: 'class fs::File' has no member named 'path'
                 if (levels) _showFiles(fs, file.path(), levels - 1);

**Comment by GyverLibs** [comment]
Нет, "плата" всё ещё не обновлена, версия ниже 2.х

**Comment by osintaras** [comment]
Но выше 1.0.6 не дает https://disk.yandex.ru/i/nwYxb4FQ4CAaIg

**Comment by GyverLibs** [comment]
Значит открываем и читаем официальную инструкцию https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html

**Comment by GyverLibs** [comment]
Или в описании портала
https://github.com/GyverLibs/GyverPortal/wiki/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B
