### ISSUE TITLE
Немогу подобрать метод

### ISSUE THREAD

**Issue by DoctorDeatch** [GyverLibs/GyverPortal#54]
Приветствую, подскажите какой метод мне бы необходимо использовать для следующей задачи:
форма простой посылки команды ping 
одно поля с IP адресом и необходимость чтобы в тоже окно с формой вернулся ответ
[https://disk.yandex.ru/i/ODTfwwe5ILCpSA](https://disk.yandex.ru/i/ODTfwwe5ILCpSA)

**Comment by GyverLibs** [comment]
Привет, есть всего два варианта передать данные на страницу: 
- Передать в конструктор (выведется при загрузке страницы) 
- Отправить в ответ на update, например в label. Либо использовать встроенный готовый инструмент log (area_log), который внутри также работает через апдейт
