### ISSUE TITLE
маленький баг

### ISSUE THREAD

**Issue by DoctorDeatch** [GyverLibs/GyverPortal#56]
обнаружился маленький баг.

в GP.SWITCH перепутаны местами параметры "цвет" и "RO"
если GP.SWITCH("eth",eth_on,GP_BLACK,0); то цвет не устанавливается и переключатель блокируется 
в реале  работает GP.SWITCH("eth",eth_on,0,GP_BLACK);

**Comment by GyverLibs** [comment]
В актуальной версии код такой, документация тоже соответствует
```cpp
void SWITCH(const String& name, bool state = 0, PGM_P st = GP_GREEN, bool dis = false)
```

**Comment by DoctorDeatch** [comment]
возможно , у меня версия GyverPortal@^3.3

**Comment by GyverLibs** [comment]
В 3.4 изменился порядок вызова
```
У CHECK и SWITCH можно выбрать цвет, ПОРЯДОК АРГУМЕНТОВ ИЗМЕНЁН
```

> шрифты в ней мне меньше понравились

Какие шрифты?
