### ISSUE TITLE
Ошибка при компилировании в Platformio "mime::getContentType(file.name()));" 

### ISSUE THREAD

**Issue by Depech101** [GyverLibs/GyverPortal#57]
mime::getContentType(file.name())); Возникает ошибка что mime должен быть именем типа.GyverPortal-main/src/portal.h:1189:33: error: 'mime' has not been declared
В библиотеке ESP32webserver есть namespace с таким именем, но нет мембера: getContentType.
От куда у этого mime ноги растут?
Так компилируется без проблем:
![изображение](https://user-images.githubusercontent.com/105047275/210825135-233869fc-2f5a-4afc-bc39-c8d5e9931388.png)

**Comment by GyverLibs** [comment]
ой, в очко эту esp32...
