### ISSUE TITLE
Многостраничность

### ISSUE THREAD

**Issue by ReMiners** [GyverLibs/GyverPortal#6]
Каким образом создается многостраничность? 
К примеру http://ip/menu/
http://ip/login

**Comment by VerZsuT** [comment]
Возможно такое решение сработает.
Создать три функции: разветвитель и два билдера страниц (либо больше).
Разветвитель передать в portal, а внутри, в зависимости от условия, вызывать билдер первой страницы либо второй.

```cpp
void loginPage() {
     // Build login page
}

void menuPage() {
    // Build menu page
}

void build() {
    if (/* condition */)
        loginPage();
    else
        menuPage();
}

void setup() {
    portal.attachBuild(build);
    portal.start();
}
```

**Comment by GyverLibs** [comment]
Это не то, будет всё ещё одна страница, как в примере menuTabs
