### ISSUE TITLE
Ошибка компиляции на esp32 Dev kit 'class fs::File' has no member named 'path'

### ISSUE THREAD

**Issue by KNikolaich** [GyverLibs/GyverPortal#60]
Установил последние на данный момент библиотеки v3.5.1. Пробую компильнуть пример типа **pageTitle** 
Результата, - \GyverPortal\src/builder.h:1123:49: error: 'class fs::File' has no member named 'path'
                 if (levels) _showFiles(fs, file.path(), odir, levels - 1);

Не очень понятно, почему он пытается компилировать CustomOTA.h ... я вроде бы в данном случае OTA не использовал.

============ полный текст ошибки =======================================================
In file included from c:\Users\user\Documents\Arduino\libraries\GyverPortal\src/CustomOTA.h:6:0,
                 from c:\Users\user\Documents\Arduino\libraries\GyverPortal\src/portal.h:18,
                 from c:\Users\user\Documents\Arduino\libraries\GyverPortal\src/GyverPortal.h:57,
                 from C:\Users\user\AppData\Local\Temp\.arduinoIDE-unsaved202309-9544-1588ppq.quf1\pageTitle\pageTitle.ino:6:
c:\Users\user\Documents\Arduino\libraries\GyverPortal\src/builder.h: In member function 'void Builder::_showFiles(fs::FS*, const String&, const String&, uint8_t)':
c:\Users\user\Documents\Arduino\libraries\GyverPortal\src/builder.h:1123:49: error: 'class fs::File' has no member named 'path'
                 if (levels) _showFiles(fs, file.path(), odir, levels - 1);
                                                 ^
Несколько библиотек найдено для "WiFiUdp.h"
  Используется: C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
  Не используется: C:\Users\user\Documents\Arduino\libraries\WiFi
exit status 1

Compilation error: exit status 1

**Comment by GyverLibs** [comment]
![image](https://user-images.githubusercontent.com/84599917/211360882-b7580c6a-ca09-4653-b84e-48f0b1088e9d.png)
