### ISSUE TITLE
GPfileType не определяет тип файла.

### ISSUE THREAD

**Issue by Depech101** [GyverLibs/GyverPortal#63]
В методе : String GPfileType(const String &uri)
Функция GPinList(ext, FPSTR(pgm_read_dword(_gp_ext + i))); возвращает всегда -1 вне зависимости от типа файла. 
Соответственно всегда отправляется тип файла по умолчанию, "Text/plain"
Тогда как абсолютно такой же метод из портала версии 3.0 работает совершенно верно.
например если мы открываем index.html to GPinList  первый раз возвращает -1 а второй 2 и все работает корректно.

**Comment by Depech101** [comment]
Дополнение.
В методе GPinList обнаружилось несоответствие
 В версии3.5 t = li.lastIndexOf(s, p);
 В версии3.0 t = li.indexOf(s, p);
Сделал как в 3.0 все заработало.

![изображение](https://user-images.githubusercontent.com/105047275/213479162-1bd5076a-6c66-47aa-a172-a93928787dae.png)

**Comment by GyverLibs** [comment]
спасибо. Осталось вспомнить, зачем был сделан `lastIndexOf`...

**Comment by Depech101** [comment]
Все таки, концепцию Clean code не зря придумали, попробуйте описывать переменные более емко, этого всегда не хватает.

**Comment by GyverLibs** [comment]
кажется цель была обрабатывать сжатые .gz файлы, и данный lastIndexOf должен был быть в строке 20 ultis.cpp, чтобы брать последнее расширение после последней точки 🤦‍♂️

**Comment by GyverLibs** [comment]
не в названиях дело, функцией ошибся)

**Comment by Depech101** [comment]
Да конечно) Спасибо за ваш труд.

**Comment by GyverLibs** [comment]
спасибо за репорт, кто знает к чему этот косячок мог бы привести 🙈🙈🙈🙈

**Comment by Depech101** [comment]
Главное картинки браузер открывал которые я из корня запускал а html выводил как текст
