### ISSUE TITLE
error : call of overloaded 'answer(unsigned char&, int&)' is ambiguous  portal.h 

### ISSUE THREAD

**Issue by Depech101** [GyverLibs/GyverPortal#66]
error : call of overloaded 'answer(unsigned char&, int&)' is ambiguous template <typename T> 
:829 bool updateFloat(const String &n, T f, int dec = 2) {
    return update(n) ? (answer(f, dec), 1) : 0;
  }
 :788  bool answer(float v, uint8_t dec) { return answer(String(v, (uint16_t)dec)); }
Заменил на:
:829 bool updateFloat(const String &n, T f, int dec = 2) {
    return update(n) ? (answer**F**(f, dec), 1) : 0;
  }
 :788  bool answer**F**(float v, uint8_t dec) { return answer(String(v, (uint16_t)dec)); }
Видимо конфликтовало с конструктором для double.

**Comment by GyverLibs** [comment]
При сообщении о багах или некорректной работе библиотеки нужно обязательно указывать:
- Версия библиотеки
- Какой используется МК
- Версия SDK (для ESP)
- Версия Arduino IDE

**Comment by Depech101** [comment]
Прощу прощения. Только начал жаловаться))

**Comment by GyverLibs** [comment]
В актуальной версии вижу да, float и double, у есп компилятора с ними постоянно проблемы. Заменю на шаблон пожалуй

**Comment by Depech101** [comment]
Значит это не я сошёл с ума))

**Comment by GyverLibs** [comment]
я закинул в репозиторий фикс, попробуй на своём коде

**Comment by Depech101** [comment]
Да все шикарно компилится, спасибо.
