### ISSUE TITLE
Не совсем понятен алгоритм работы форм.

### ISSUE THREAD

**Issue by Depech101** [GyverLibs/GyverPortal#67]
Версия библиотеки - 3.5
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/lolin_s2_mini.html
PLATFORM: Espressif 32 (6.0.0) > WEMOS LOLIN S2 Mini 
HARDWARE: ESP32S2 240MHz, 320KB RAM, 4MB Flash - 
IDE Platformio 
PACKAGES:
- framework-arduinoespressif32 @ 3.20006.221224 (2.0.6)
- tool-esptoolpy @ 1.40400.0 (4.4.0)
- toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
- toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch5
Имеем такой блок с формой.

![изображение](https://user-images.githubusercontent.com/105047275/215560501-7c911cee-6e00-4ec0-af04-e3196b74002e.png)
GP_MAKE_BLOCK(
  GP_MAKE_BOX(GP_CENTER, GP.LABEL("Ширина шины");); GP_MAKE_BOX(GP_CENTER, GP.SPINNER("tireWide", tireWide, 0, 500, 1, 0, GP_GREEN, "200px"););
  GP_MAKE_BOX(GP_CENTER, GP.LABEL("Высота профиля");); GP_MAKE_BOX(GP_CENTER, GP.SPINNER("tireHigh", tireHigh, 0, 100, 1, 0, GP_GREEN, "200px"););
  GP_MAKE_BOX(GP_CENTER, GP.LABEL("Радиус R");); GP_MAKE_BOX(GP_CENTER, GP.SPINNER("radiusOfWheel", radiusOfWheel, 0, 20, 1, 0, GP_GREEN, "200px"););
  GP_MAKE_BOX(GP_LEFT, GP.LABEL("Длинна окружности ");
              GP.NUMBER_F("lengthResult", "lengthResult", lengthResult, 2, "85px");); /* GP_MAKE_BOX(GP_LEFT, GP.LABEL("", "diametrResult"););); */
  GP_MAKE_BOX(GP_JUSTIFY,GP.BUTTON_MINI("calculation", " Расчёт ","tireCalculation");GP.SUBMIT_MINI("Сохранить");););
При нажатии на кнопку метод portal.clickDown возвращает true что хорошо. и можно по этому условию как то уйти от обновления формы. Но при это еще срабатывает SUBMIT этой формы, как то не логично, зачем тогда дедать ;GP.SUBMIT_ если он ни как не работает отдельно а форма срабатывает на любую кнопку.

**Comment by GyverLibs** [comment]
Зачем каждая строчка в BOX? Можно задать выравнивание всему BLOCK, не нужно всё пихать в боксы) Перенос строки - BREAK.
По теме вопроса - это приколы html, любая кнопка внутри формы зачем то приводит к submit. Попробую как нибудь обойти в следующем обновлении

**Comment by GyverLibs** [comment]
```cpp
  M_BLOCK(
    GP.LABEL("Ширина шины");
    GP.SPINNER("tireWide", 0, 0, 500, 1, 0, GP_GREEN, "200px");
    GP.BREAK();
    GP.LABEL("Высота профиля");
    GP.SPINNER("tireHigh", 0, 0, 100, 1, 0, GP_GREEN, "200px");
    GP.BREAK();GP.BREAK();
    GP.LABEL("Радиус R");
    GP.SPINNER("radiusOfWheel", 0, 0, 20, 1, 0, GP_GREEN, "200px");
    GP.BREAK();GP.BREAK();
    GP.LABEL("Длина ");
    GP.NUMBER_F("lengthResult", "lengthResult", 0, 2, "85px");
    M_BOX(GP_JUSTIFY, GP.BUTTON_MINI("calculation", " Расчёт "); GP.SUBMIT_MINI("Сохранить"););
  );
```

**Comment by Depech101** [comment]
Благодарю, дальше пошел искать к чему придраться))
Нет мыслей делать более подробные примеры, может быть в папки с примерами
класть сразу картинку страницы которую они генерят, мне бы такое зашло.
К стати, GP.FORM_SEND  не приводит к отправке формы. Может сейчас
исправилось, надо проверить.

**Comment by GyverLibs** [comment]
Мысли есть, времени нет

**Comment by Depech101** [comment]
Так и подумал, может я помогу? хотя бы по тому что есть пока. В виде Pull recuest полагаю?

**Comment by GyverLibs** [comment]
по хорошему нужно просто дописать документацию с примерами и советами по вёрстке из стандартных компонентов) примеры в основе свой функциональные, а не для дизайна

**Comment by Depech101** [comment]
По мере возможностей нужно заняться. 
А по поводу:

> сделал, обновил в репозитории. Релиз пока не публикую

Стало хуже, SUMIT_MINI приводит только к срабатыванию action но не формы.

**Comment by GyverLibs** [comment]
> Стало хуже, SUMIT_MINI приводит только к срабатыванию action но не формы.

всё в порядке? Мне на почту это пришло, а тут в диалоге нету

**Comment by Depech101** [comment]
Поторопился чуток,проверю отпишусь, есть сомнения.

**Comment by Depech101** [comment]
Кнопка GP.BUTTON_MINI("calculation", " Расчёт ", "tireCalculation", GP_GREEN, "", 0, 1);
Не перезагружает страницу, но action работает.
Возможно проблема со скриптом? 
Тут: builder.h :1334
  } else {
            *_GPP += F("onclick='GP_click(this,");
            *_GPP += rel;
            *_GPP += F(")'");
        }  
все вроде ок.

**Comment by Depech101** [comment]
![изображение](https://user-images.githubusercontent.com/105047275/216340613-514e29bf-3b62-4293-89a6-899407770273.png)

**Comment by GyverLibs** [comment]
Что то на.бнулось, починю

**Comment by Depech101** [comment]
> Что то на.бнулось, починю

Шойто не починилось еще)

**Comment by GyverLibs** [comment]
не было времени заняться. Значение с какого компонента отправляет кнопка?

**Comment by GyverLibs** [comment]
судя по ошибке - задан таргет на несуществующий элемент на странице
