### ISSUE TITLE
Передача списка сете в Select и передача всех поле на странице по клику кнопки

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [GyverLibs/GyverPortal#69]
Всем привет!
Что то я совсем запутался...
Это одна из стандартных задач для любого Web интерфейса, но я не смог найти ни одного примера реализации.
Есть функция (стандартный алгоритм поиска сетей для ESP32).
Я хочу получить список найденных сетей на Web странице в элементе Select с остальными полями (пароль и т.д.) и по нажатию кнопки Сохранить - сформировать что то типа JSON объекта и передать назад в ESP, там разобрать пакет и т.д.
Проблема именно с реализацией взаимодействия с Web интерфейсом. JSON не обязателен, можно передать как то иначе, в каждый обработчик поля например, не важно.
```cpp
{
  "sta_ssid":"val_ssid_sta",
  "sta_psk":"val_pas_sta",
  "ap_ssid":"val_ssid_ap",
  "ap_psk":"val_pas_ap",
  /* и так далее... */
}
```
Подскажите, как это сделать?

**Comment by GyverLibs** [comment]
> Это одна из стандартных задач для любого Web интерфейса

Можно пример?

> стандартный алгоритм поиска сетей ... с остальными полями (пароль и т.д.)

Esp32 умеет сканировать и сразу взламывать точки?

**Comment by Oleg-Perevyshin** [comment]
1. Ну как же, в первую очередь нужно подключить WiFi модуль либо к существующей сети, либо поднять свою точку доступа, а так от модуля нет толку (точнее не все его возможности используются).

2. Взламывать)) Нет, она просто может выдать список сетей с набором параметров (SSID, канал, шифрование и т.д.)
Я сейчас спокойно (по вызову функции) получаю список обнаруженных SSID, а вот дальше что с ним делать, как передать в Web не знаю, незадача)

**Comment by GyverLibs** [comment]
1. Полностью готовый пример с хранением настроек в епром https://github.com/GyverLibs/GyverPortal/blob/main/examples/projects/wifiLogin/wifiLogin.ino
2. Список ssid можно передать в выпадающий список как в первых трёх примерах в папке demo. Куда выводить остальную информацию о точках - вопрос дизайна. Зачем передавать эту информацию из браузера обратно в есп тоже не очень понятно, потому что эту информацию есп получает не из браузера

**Comment by Oleg-Perevyshin** [comment]
Буду разбираться, благодарю!
Потом сюда скину рабочий код, мало ли кому пригодится)
