### ISSUE TITLE
Сохранение SSID и PASS 

### ISSUE THREAD

**Issue by IljaGolenev** [GyverLibs/GyverPortal#72]
Используя библиотеку GyverPortal пишу в GP.BUILD следующее

 GP.TEXT("apLogin","Логин для авторизации",data.AP_LOGIN);
 GP.PASS_EYE("apPass","Пароль для авторизации",data.AP_PASS);

в void action() в условии эти элементы опрашиваются и забираются у них значения этим:

 data.AP_LOGIN = ui.getString("apLogin");
 ui.copyStr("apPass", data.AP_PASS);

Что бы в конечном итоге скормить переменные AP_PASS и AP_SSID сюда:
WiFi.begin(data.AP_SSID, data.AP_PASS);

В структуре написано следующее:
struct Data {
bool valSwitch;
char STA_SSID;
char STA_PASS;
char AP_SSID;
char AP_PASS;
char AP_LOGIN;
};
Data data;
(я и с char, и со String пробовал)

Только вот на этой самой строке с WiFi.begin компилятор выдает, что преобразование из 'char' в 'const String' неоднозначно, когда переменные объявлены как char/
А когда объявлены как String, то пишет в строке с ui.enableAuth, что не может преобразовать "String" в "const char*"

Задача состоит в том, что бы в режиме точки доступа можно было указать SSID и пароль для этой же точки доступа и для режима STA, а затем сохранить с помощью библиотеки EEManager.

Как-то можно преобразовать или сделать свой объект по типу GP_TEXT и GP_PASS только с возвратом нужных типов данных?
пример selectBuild из библиотеки GyverPortal может помочь?
Приложил фото для удобства.
![image](https://user-images.githubusercontent.com/88191098/222908363-b26e6704-cde3-4200-bdaa-1bb65892c91d.png)
![image](https://user-images.githubusercontent.com/88191098/222908370-aff46741-460f-4d83-b07c-639770cd1e71.png)
![image](https://user-images.githubusercontent.com/88191098/222908378-c1b4cb19-f7e9-4303-9d5b-8b8da6b8b8b7.png)

**Comment by GyverLibs** [comment]
Так нельзя!! char это символ, строка это char*, то есть char[]
![image](https://user-images.githubusercontent.com/84599917/222911344-b83bc10b-d411-4e24-ba22-acd75c68c7cd.png)

См встроенный пример https://github.com/GyverLibs/GyverPortal/blob/main/examples/projects/wifiLogin/wifiLogin.ino
