### ISSUE TITLE
Обновление страницы по portal.click()

### ISSUE THREAD

**Issue by n0t-amused** [GyverLibs/GyverPortal#74]
Добрый день!

Никак не могу раскурить как прикрутить GP.RELOAD() к компонену, обновляемому по portal.click(). Пример:

На странице есть GP.SPINNER с режимами работы. Для каждого режима значения задаются своим набором компонентов (слайдеров, в моем случае). Нужно, чтобы при выборе значения GP.SPINNER страница обновлялась для отрисовки нужных мне слайдеров. Нужные слайдеры получилось реализовать банальным набором if в конструкторе, привязываясь к значению переменной, выбираемой GP.SPINNER. Нужные мне слайдеры показываются при обновлении страницы вручную.

А вот приделать GP.RELOAD к условию if (portal.clickInt(мой спиннер)) - не получается. Пробовал описанный в вики пример с 
`if (portal.update("rel")) portal.answer(1);` внутри условия if(portal.clickInt)... - но не взлетает.

**Comment by GyverLibs** [comment]
привет, смотри пример builds/selectBuild

**Comment by n0t-amused** [comment]
> привет, смотри пример builds/selectBuild

А, видимо `GP.RELOAD_CLICK(компонент)` именно то что мне и нужно было. Спасибо, попробую вечером!

**Comment by GyverLibs** [comment]
это более удобный и правильный способ сделать динамическую страницу, RELOAD по ответу устарел

**Comment by n0t-amused** [comment]
Да, все отлично работает одной строчкой. Спасибо!
