### ISSUE TITLE
Почему может не работать DNS сервер?

### ISSUE THREAD

**Issue by kbln** [GyverLibs/GyverPortal#75]
Версия библиотеки **3.6.3**
МК **esp8266**
Версия SDK **3.1.1**
Версия Arduino IDE **1.8.19**

При прошивке вашего проекта wifiLogin в режиме WIFI_AP редирект не срабатывает, хотя по идее должен.
При этом, стандартные примеры DNS сервера работают, а через Портал почему-то нет( 
В чем может быть проблема? У вас редирект работает?

**Comment by GyverLibs** [comment]
Какой редирект? Dns позволяет найти плату по имени.local, редиректа не должно быть

**Comment by kbln** [comment]
Сорри, может непонятно выразился, ты говоришь про MDNS (он работает), а я про DNSServer, который должен перенаправлять нас на айпишник esp при подключении, но почему-то не перенаправляет

**Comment by GyverLibs** [comment]
Хм. А его как то отдельно включать можно?

**Comment by AlexGyver** [comment]
Ого, вот это интересно, спасибо.... надо чинить

**Comment by AlexGyver** [comment]
а у меня работает нормально...

**Comment by AlexGyver** [comment]
поддержка скачивания не должна влиять. Если скачивание не настроено, файл запрошен но юзер его не отправил - сервер ответит 200, точно так же как если отключить поддержку скачивания

**Comment by kbln** [comment]
Мне тоже это кажется странным, но перепроверил еще раз, без этого дефайна у меня редирект не работает
```
#define GP_NO_DOWNLOAD      // без этого не работает DNSServer

#include <GyverPortal.h>
GyverPortal ui;

void build() {
  GP.BUILD_BEGIN(GP_DARK);
  GP.TITLE("Hello!");
  GP.BUILD_END();
}

void setup() {
  WiFi.mode(WIFI_AP);
  WiFi.softAP("WiFi Config");

  ui.attachBuild(build);
  ui.start();
}

void loop() {
  ui.tick();
}
```

**Comment by AlexGyver** [comment]
дефайн закрывает всего два места в коде, можно определить какое. В portal.h попробуй закомментировать по очереди их, сам дефайн в скетче соответственно не нужен

```
    #ifdef GP_NO_DOWNLOAD
} else if (_uri.startsWith(F("/favicon.ico"))) {    // иконка
    server.send(200);
    return;
    #endif
```
```
    #if defined(FS_H) && !defined(GP_NO_DOWNLOAD)
} else if (downOn && !server.args() && _uri[0] == '/' && _uri.indexOf('.') > 0) {   // файл
    if (_autoD && _fs) sendFile(_fs->open(_uri, "r"));  // авто скачивание
    else _fileDF = 1;                                   // ручное скачивание (в action)
    #endif
```

**Comment by AlexGyver** [comment]
также в самое начало `server.onNotFound([this]() {` можно добавить вывод в порт, посмотреть что телефон запрашивает у сервера

```cpp
Serial.print(server.uri());
if (server.args()) {
    Serial.print('?');
    for (int i = 0; i < server.args(); i++) {
        Serial.print(server.argName(i));
        Serial.print('=');
        Serial.print(server.arg(i));
        if (i < server.args() - 1) Serial.print('&');
    }
}
Serial.println();
```

**Comment by kbln** [comment]
проблема где-то тут
```
    #if defined(FS_H) && !defined(GP_NO_DOWNLOAD)
} else if (downOn && !server.args() && _uri[0] == '/' && _uri.indexOf('.') > 0) {   // файл
    if (_autoD && _fs) sendFile(_fs->open(_uri, "r"));  // авто скачивание
    else _fileDF = 1;                                   // ручное скачивание (в action)
    #endif
```

**Comment by AlexGyver** [comment]
нужно отладочный кусок вставить, посмотреть что запрашивает клиент

**Comment by AlexGyver** [comment]
я бы сам поковырялся, но у меня работает) не могу повторить баг

**Comment by kbln** [comment]
Это выдало без дефайна `/hotspot-detect.html`
Это с дефайном:
```
/hotspot-detect.html
/hotspot-detect.html
/hotspot-detect.html
/GP_STYLE.css?v3.6.3=44089
/GP_SCRIPT.js?v3.6.3=0
/GP_time?unix=1679052377&gmt=360
/hotspot-detect.html
```

**Comment by AlexGyver** [comment]
вот это интересно, мой андроид не запрашивает такого. Ну тогда понятно что происходит - смарт запрашивает страницу hotspot-detect.html, портал показывает ему дулю `200`, а при отключенном DOWNLOAD портал отправляет страницу

**Comment by AlexGyver** [comment]
добавить код
```cpp
} else if (_uri.startsWith(F("/hotspot-detect.html"))) {
    _showPage = 1;
```

например вот сюда
![image](https://user-images.githubusercontent.com/21090953/225893430-6b5f8258-d7cc-434d-9022-774935aba296.png)

**Comment by AlexGyver** [comment]
если заведётся, добавлю в обновление тогда

**Comment by kbln** [comment]
Сработало!

**Comment by AlexGyver** [comment]
отлично, тогда эту заплатку добавлю себе)
