### ISSUE TITLE
Редирект на другую страницу

### ISSUE THREAD

**Issue by KyKyIIIKuH** [GyverLibs/GyverPortal#88]
Было бы не плохо добавить по умолчанию функцию редиректа на другую страницу
столкнулся с такой проблемой, когда отправляется форма, появляется главная страница
решил проблему добавив функцию редиректа

в файл builder.h добавил следующее
```
   // Редирект
    void REDIRECT(const String& name) {
        _gp_s->sendHeader("Location", String(name), true);
        _gp_s->send ( 302, "text/plain", "");
    }
```

Pull requests  не умею делать, так что решил написать сюда

**Comment by GyverLibs** [comment]
в библиотеке есть вариант send_form с указанием редиректа

**Comment by KyKyIIIKuH** [comment]
Опа, не заметил, спасибо за то что открыл глаза ☺️

**Comment by KyKyIIIKuH** [comment]
Опа, не заметил, спасибо за то что открыл глаза ☺️
