### ISSUE TITLE
Примеры работы со временем

### ISSUE THREAD

**Issue by vectorman115** [GyverLibs/GyverPortal#90]
В SYSTEM_INFO выводится время и дата.
К сожалению из документации и исходников я не понял, как можно в какой-нибудь функции (например, в loop) получить текущее значнеие времени. Нужно ли для этого делать отдельную логику (например на модуле RTC) или все-таки GP предоставляет такую возможность?

**Comment by GyverLibs** [comment]
[Вот тут](https://github.com/GyverLibs/GyverPortal/wiki#%D0%BA%D0%BB%D0%B0%D1%81%D1%81-gyverportal) в документации, вкладка **Система**
```cpp
// ================ ВРЕМЯ ===============
GPdate getSystemDate();         // получить текущую дату
GPtime getSystemTime();         // получить текущее время
uint32_t getUnix();             // получить текущее unix время
```
Время приходит из браузера и дальше считается средствами esp (миллис), соответственно чтобы время работало - после загрузки МК нужно хотя бы один раз открыть портал

**Comment by GyverLibs** [comment]
Использовать например так:
```cpp
GPtime time = portal.getSystemTime();
Serial.println(time.hour);
```

**Comment by vectorman115** [comment]
Спасибо!
До вот этого я додумался:
GPtime time = portal.getSystemTime();
Serial.println(time.hour);

А вот до того, что надо сначала войти через браузер - нет.
