### ISSUE TITLE
График X Y

### ISSUE THREAD

**Issue by DEST1981** [GyverLibs/GyverPortal#92]
Может кто подскажет есть ли возможность выводить обычный  X Y график?

**Comment by ran075** [comment]
Такой?
![Screenshot - 12 01 2024 , 20_30_58](https://github.com/GyverLibs/GyverPortal/assets/56223740/fabe6ffc-d2ed-488c-b1ee-2e3cd1af8afb)

Смотри в описании библиотеки https://github.com/GyverLibs/GyverPortal/wiki/Графики

А также примеры кода в Ардуино  
![Screenshot - 12 01 2024 , 20_27_36](https://github.com/GyverLibs/GyverPortal/assets/56223740/082ade91-5372-44e3-9661-134258861439)
